# Generated by Django 5.2.1 on 2025-06-04 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_constructionobject_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionobject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
