# Generated by Django 5.2.1 on 2025-06-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_constructionobject_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionobject',
            options={'verbose_name': 'Qurilish Loyihasi', 'verbose_name_plural': 'Qurilish Loyihalari'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aniqlangan kamchilik', 'verbose_name_plural': 'Aniqlangan kamchiliklar'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tekshiruv hisoboti', 'verbose_name_plural': 'Tekshiruv Hisobotlari'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-planned_date'], 'verbose_name': 'Tekshiruv', 'verbose_name_plural': 'Tekshiruvlar'},
        ),
    ]
