# Generated by Django 5.2.1 on 2025-06-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_constructionobject_options_alter_issue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
