# Generated by Django 5.2.1 on 2025-06-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionObjectDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True, verbose_name='Majburiy?')),
                ('required_for_business', models.BooleanField(default=True, verbose_name='Xususiy sektor uchun majburiy?')),
            ],
            options={
                'verbose_name': 'Hujjat turi',
                'verbose_name_plural': 'Hujjat turlari',
            },
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='is_government',
            field=models.BooleanField(default=False, verbose_name='Davlat qurilish obyekti?'),
        ),
        migrations.CreateModel(
            name='ConstructionObjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.constructionobject')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.constructionobjectdocumenttype', verbose_name='Hujjat turi')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
    ]
