# Generated by Django 5.2.1 on 2025-06-14 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_constructionobjectdocumenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Qurilish tashkiloti',
                'verbose_name_plural': 'Qurilish tashkilotlari',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_level',
            field=models.CharField(choices=[('red', 'Qizil'), ('yellow', 'Sariq'), ('green', 'Yashil')], default='green', max_length=10),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolve_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Ochiq'), ('in_progress', 'Bartaraf etilmoqda'), ('resolved', 'Bartaraf etildi')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='construction_companies',
            field=models.ManyToManyField(to='api.constructioncompany'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hodim',
                'verbose_name_plural': 'Hodimlar',
            },
        ),
        migrations.AddField(
            model_name='constructioncompany',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_companies_as_contact', to='api.person'),
        ),
        migrations.AddField(
            model_name='constructioncompany',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_companies_as_director', to='api.person'),
        ),
        migrations.CreateModel(
            name='ProjectDeveloperCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_companies_as_contact', to='api.person')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_companies_as_director', to='api.person')),
            ],
            options={
                'verbose_name': 'Loyiha tashkiloti',
                'verbose_name_plural': 'Loyiha tashkilotlari',
            },
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='project_companies',
            field=models.ManyToManyField(to='api.projectdevelopercompany'),
        ),
    ]
