# Generated by Django 5.2.1 on 2025-06-14 11:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_issuetype_issue_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructioncompany',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='constructioncompany',
            name='personal',
            field=models.ManyToManyField(to='api.person'),
        ),
        migrations.AddField(
            model_name='constructioncompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectdevelopercompany',
            name='personal',
            field=models.ManyToManyField(to='api.person'),
        ),
    ]
