# Generated by Django 5.2.1 on 2025-06-16 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_constructioncompany_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuephoto',
            options={'verbose_name': 'Foto', 'verbose_name_plural': 'Foto'},
        ),
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
