# Generated by Django 5.2.1 on 2025-09-26 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_issuephoto_options_alter_person_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructioncompany',
            name='inn',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='objects/'),
        ),
        migrations.AddField(
            model_name='projectdevelopercompany',
            name='inn',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.CreateModel(
            name='ProjectOwnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('inn', models.CharField(default='00000000', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_companies_as_contact', to='api.person')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_companies_as_director', to='api.person')),
                ('personal', models.ManyToManyField(to='api.person')),
            ],
            options={
                'verbose_name': 'Loyiha tashkiloti',
                'verbose_name_plural': 'Loyiha tashkilotlari',
            },
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='owner_companies',
            field=models.ManyToManyField(to='api.projectownercompany'),
        ),
    ]
