# Generated by Django 5.2.1 on 2025-09-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_constructioncompany_inn_constructionobject_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tekshiruv turi',
                'verbose_name_plural': 'Tekshiruv turlari',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='inspection_types',
            field=models.ManyToManyField(to='api.inspectiontype'),
        ),
    ]
