# Generated by Django 5.2.1 on 2025-10-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('supervisor', 'Inspektor'), ('admin', 'Admin'), ('owner', 'Buyurtmachi'), ('developer', 'Loyihachi'), ('builder', 'Quruvchi'), ('prokuratura', 'Prokuratura'), ('control', 'Nazorat')], default='worker', max_length=20),
        ),
    ]
