# Generated by Django 5.2.1 on 2025-10-09 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('resolved', 'Bartaraf etildi'), ('rejected', 'Rad etish')], default='resolved', max_length=20)),
                ('report', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_actions', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.issue')),
            ],
            options={
                'verbose_name': 'Kamchilik ustida amaliyot',
                'verbose_name_plural': 'Kamchilik ustida amaliyotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueActionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='report_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issue_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.issueaction')),
            ],
            options={
                'verbose_name': 'Amaliyot fotosi',
                'verbose_name_plural': 'Amaliyot fotolari',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_comments', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.review', verbose_name='Tekshiruv')),
            ],
            options={
                'verbose_name': 'Tekshiruv hisoboti izohi',
                'verbose_name_plural': 'Tekshiruv hisoboti izohlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCommentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='comment_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reviewcomment')),
            ],
            options={
                'verbose_name': 'Amaliyot fotosi',
                'verbose_name_plural': 'Amaliyot fotolari',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
