# Generated by Django 5.2.1 on 2026-05-16 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_issueaction_issueactionphoto_reviewcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tuman|Shahar',
                'verbose_name_plural': 'Tuman|Shaharlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GovermentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name="Qaror to'liq nomi")),
                ('code', models.CharField(max_length=100, verbose_name='Qaror raqami')),
                ('description', models.TextField(blank=True, null=True, verbose_name="Qisqacha ma'lumot")),
                ('budget', models.FloatField(blank=True, null=True, verbose_name="Ajratilgan mablag'")),
            ],
            options={
                'verbose_name': 'Davlat dasturi',
                'verbose_name_plural': 'Davlat dasturlari',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='constructionobject',
            options={'ordering': ('name',), 'verbose_name': 'Qurilish Loyihasi', 'verbose_name_plural': 'Qurilish Loyihalari'},
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='budget',
            field=models.FloatField(blank=True, null=True, verbose_name="Ajratilgan mablag' (mln. so'mda)"),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='building_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Obyektlar soni'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='contract_amount',
            field=models.FloatField(blank=True, null=True, verbose_name="Shartnoma qiymati (mln. so'mda)"),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='machines',
            field=models.PositiveSmallIntegerField(default=0, help_text='Qurilishga jalb qilingan texnikalar soni', verbose_name='Texnikalar'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='radius',
            field=models.FloatField(default=200, verbose_name='Qurilish radiusi'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='workers',
            field=models.PositiveSmallIntegerField(default=1, help_text='Qurilishga jalb qilingan ishchilar soni', verbose_name='Ishchilar'),
        ),
        migrations.AlterField(
            model_name='constructionobject',
            name='address',
            field=models.TextField(verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='constructionobject',
            name='construction_companies',
            field=models.ManyToManyField(to='api.constructioncompany', verbose_name='Qurilish tashkilotlari'),
        ),
        migrations.AlterField(
            model_name='constructionobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='constructionobject',
            name='owner_companies',
            field=models.ManyToManyField(to='api.projectownercompany', verbose_name='Buyurtmachi tashkilotlar'),
        ),
        migrations.AlterField(
            model_name='constructionobject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='objects/', verbose_name='Loyiha rasmi'),
        ),
        migrations.AlterField(
            model_name='constructionobject',
            name='project_companies',
            field=models.ManyToManyField(to='api.projectdevelopercompany', verbose_name='Loyihachi tashkilotlar'),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='api.govermentprogram', verbose_name='Davlat dasturi'),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.neighborhood', verbose_name='Mahalla'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.region'),
        ),
    ]
