# Generated by Django 5.2.1 on 2026-05-16 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_district_govermentprogram_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectownercompany',
            options={'verbose_name': 'Buyurtmachi tashkilot', 'verbose_name_plural': 'Buyurtmachi tashkilotlar'},
        ),
    ]
