# Generated by Django 5.2.1 on 2026-05-16 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_projectownercompany_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionobject',
            name='attached_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_objects', to='api.person', verbose_name="Ma'sul hodim"),
        ),
    ]
