# Generated by Django 5.2.1 on 2026-05-16 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_constructionobject_attached_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionobject',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.govermentprogram', verbose_name='Davlat dasturi'),
        ),
    ]
