# Generated by Django 5.2.1 on 2026-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_constructionobject_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionobject',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Nomi'),
        ),
    ]
