# Generated by Django 5.2.1 on 2026-05-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_constructionobject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructioncompany',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_companies_as_contact', to='api.person', verbose_name="Ma'sul hodim"),
        ),
        migrations.AlterField(
            model_name='constructioncompany',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tashkilot haqida'),
        ),
        migrations.AlterField(
            model_name='constructioncompany',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_companies_as_director', to='api.person', verbose_name='Rahbari'),
        ),
        migrations.AlterField(
            model_name='constructioncompany',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Tashkilot nomi'),
        ),
        migrations.AlterField(
            model_name='projectdevelopercompany',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_companies_as_contact', to='api.person', verbose_name="Ma'sul hodim"),
        ),
        migrations.AlterField(
            model_name='projectdevelopercompany',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tashkilot haqida'),
        ),
        migrations.AlterField(
            model_name='projectdevelopercompany',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_companies_as_director', to='api.person', verbose_name='Rahbari'),
        ),
        migrations.AlterField(
            model_name='projectdevelopercompany',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Tashkilot nomi'),
        ),
        migrations.AlterField(
            model_name='projectdevelopercompany',
            name='personal',
            field=models.ManyToManyField(to='api.person', verbose_name='Hodimlar'),
        ),
        migrations.AlterField(
            model_name='projectownercompany',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_companies_as_contact', to='api.person', verbose_name="Ma'sul hodim"),
        ),
        migrations.AlterField(
            model_name='projectownercompany',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tashkilot haqida'),
        ),
        migrations.AlterField(
            model_name='projectownercompany',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_companies_as_director', to='api.person', verbose_name='Rahbari'),
        ),
        migrations.AlterField(
            model_name='projectownercompany',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Tashkilot nomi'),
        ),
        migrations.AlterField(
            model_name='projectownercompany',
            name='personal',
            field=models.ManyToManyField(to='api.person', verbose_name='Hodimlar'),
        ),
    ]
