# Generated by Django 6.0.5 on 2026-05-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_constructioncompany_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_fullname', models.CharField(max_length=255)),
                ('issuer_phone', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('issue_level', models.CharField(choices=[('red', 'Qizil'), ('yellow', 'Sariq'), ('green', 'Yashil')], default='green', max_length=10)),
                ('resolve_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jamoatchilik qayd etgan muammo',
                'verbose_name_plural': 'Jamoatchilik qayd etgan muammolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicIssuePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='public_issue_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.publicissue')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Foto',
            },
        ),
    ]
