# Generated by Django 6.0.5 on 2026-05-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_publicissue_publicissuephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicissue',
            name='construction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructionobject'),
        ),
    ]
