# Generated by Django 6.0.5 on 2026-05-18 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_publicissue_construction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionFinancing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='Moliyalashtirilgan summa')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Moliyalashtirilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.constructionobject', verbose_name='Qurilish loyihasi')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.person', verbose_name="Ma'sul shaxs")),
            ],
            options={
                'verbose_name': 'Moliyalashtirilgan summa',
                'verbose_name_plural': 'Moliyalashtirish tarixi',
            },
        ),
    ]
