# Generated by Django 6.0.5 on 2026-05-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_constructionfinancing'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionobject',
            name='deadline',
            field=models.DateField(blank=True, help_text='Topshirish muddatining oxirgi sanasi', null=True, verbose_name='Qurilish topshirish muddati'),
        ),
        migrations.CreateModel(
            name='ConstructionDailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='Ish hajmi')),
                ('workers', models.PositiveSmallIntegerField(default=0, verbose_name='Ishchilar soni')),
                ('machines', models.PositiveSmallIntegerField(default=0, verbose_name='Texnikalar soni')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.constructionobject')),
            ],
            options={
                'verbose_name': 'Qurilish kunlik',
                'verbose_name_plural': 'Qurilish kunlik tarixi',
            },
        ),
    ]
