# Generated by Django 6.0.5 on 2026-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_constructionobject_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionobject',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'I Toifa'), (1, 'II Toifa'), (2, 'III Toifa'), (3, 'IV Toifa')], default=0),
        ),
    ]
