# Generated by Django 6.0.5 on 2026-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_constructionobject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionobject',
            name='i_reviews_p_m',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='p_reviews_p_m',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constructionobject',
            name='t_reviews_p_m',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
