# Generated by Django 6.0.5 on 2026-05-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_constructionobject_i_reviews_p_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionobject',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rejalashtirilgan'), (1, 'Boshlangan'), (2, 'Moliyalashtirilgan'), (3, 'Qurilish tugallangan'), (4, 'Foydalanishga topshirilgan'), (5, "To'xtatilgan"), (6, "Moliyalashtirish to'xtatilgan")], default=1),
        ),
    ]
