# Generated by Django 6.0.5 on 2026-05-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_constructionobject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.review'),
        ),
    ]
