# Generated by Django 6.0.5 on 2026-05-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_issue_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.constructionobject'),
        ),
    ]
