# Generated by Django 6.0.5 on 2026-05-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ochiq'), (1, 'Bartaraf etilgan'), (2, 'Bajarilmagan')], default=0),
        ),
    ]
