# Generated by Django 6.0.5 on 2026-05-22 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_assignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Biriktirilgan hodim'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Muddati'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='Murojaat matni'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.constructionobject', verbose_name='Qurilish'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ochiq'), (1, 'Bartaraf etilgan'), (2, 'Bajarilmagan')], default=0, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Sarlavha'),
        ),
    ]
