# Generated by Django 6.0.5 on 2026-06-01 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_assignment_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('supervisor', 'Inspektor'), ('admin', 'Admin'), ('owner', 'Buyurtmachi'), ('developer', 'Loyihachi'), ('builder', 'Quruvchi'), ('prokuratura', 'Prokuratura'), ('control', 'Nazorat')], default='supervisor', max_length=20),
        ),
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assignment')),
            ],
            options={
                'verbose_name': 'Murojaat fayli',
                'verbose_name_plural': 'Murojaat fayllari',
                'ordering': ('assignment',),
            },
        ),
    ]
