# Generated by Django 6.0.5 on 2026-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_user_role_assignmentattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionobject',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Rejalashtirilgan'), (1, 'Boshlangan'), (2, 'Moliyalashtirilgan'), (3, 'Qurilish tugallangan'), (4, 'Foydalanishga topshirilgan'), (5, "To'xtatilgan"), (6, "Moliyalashtirish to'xtatilgan"), (7, 'Tekshirilmoqda')], default=1),
        ),
    ]
