# Generated by Django 6.0.5 on 2026-06-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_constructionobject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='personal',
            field=models.ManyToManyField(to='api.person', verbose_name='Hodimlar'),
        ),
    ]
