# Generated by Django 6.0.5 on 2026-08-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_district_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_serial', models.CharField(max_length=64, unique=True)),
                ('channel_no', models.CharField(default='1', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='api.constructionobject')),
            ],
        ),
        migrations.CreateModel(
            name='CameraCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camera_captures/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='api.camera')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['camera', '-captured_at'], name='api_camerac_camera__d1eff1_idx')],
            },
        ),
    ]
